### ISSUE TITLE
Question about SES Domain vs Kindle Whitelisting

### ISSUE THREAD

**Issue by thesavant42** [shapeshed/kindle-crosswords#1]
Very cool script, I've been looking for something like this and it seemed like a great way to get to know the aws-cli api a bit better. 

I've got an identity configured for my gmail address, and I can send and receive to my gmail when testing without any issue, I receive the cropped PDFs. But when I try to send to my kindle email address, the message is refused. The "send from" address, my gmail, is already whitelisted in the Kindle's approved document sender settings. 

My belief is this is because I am in the sandbox, and thusly can only send to addresses I can click the verify link from; a no-go with the kindle.com addresses. Is there a way to configure this with a sandboxed SES account? I was considering setting up a rule in Gmail to automatically forward to Kindle, as a workaround.

Either way, this makes the Scribe even more useful, thank you!

**Comment by shapeshed** [comment]
You need to move out of the ses sandbox to send to domains outside of the registered one.

https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html

Alternatively you could send the email via another service but you would need to configure that differently.
